version: '2'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 10m

services:
  pb:
    image: judge0/pb:d0c2309e
    volumes:
      - ./config.yaml:/etc/xdg/pb/config.yaml
    ports:
      - "8080:8080"
    <<: *default-logging
    restart: always

  mongo:
    image: mongo:4
    volumes:
      - mongo-data:/data/db
    <<: *default-logging
    restart: always

volumes:
  mongo-data: